import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import ReduxProviders from "@/redux/reduxProvider";
import { Inter } from "next/font/google";
import "./globals.css";

// Import Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProviders>
        <body className={`${inter.variable} antialiased`}>
          <Navbar />
          <main className="">{children}</main>
          <Footer />
        </body>
      </ReduxProviders>
    </html>
  );
}
