import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

// Import Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="">
      <Navbar />
      <main className="">{children}</main>
      <Footer />
    </div>
  );
}
