import DashboardNavbar from "@/components/shared/DashboardNavbar";
import { Inter } from "next/font/google";

// Import Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="bg-[#F5F5F5] px-5 h-screen overflow-y-auto">
      {/* <nav className="h-[80px] py-3 border-b border-dashed border-gray-300">navbar</nav> */}
      <DashboardNavbar />
      <main className="">{children}</main>
      {/* <Footer /> */}
    </div>
  );
}
